apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- configmap.yaml
- auth-uploads-pvc.yaml
- auth-service-deployment.yaml
- lms-service-deployment.yaml
- lab-service-deployment.yaml
- chat-service-deployment.yaml
- ai-service-deployment.yaml
- course-blueprint-worker-deployment.yaml
- ai-model-cache-pvc.yaml
- personalize-pvc.yaml
- personalize-service-deployment.yaml
- recommender-service-deployment.yaml
- frontend-deployment.yaml
- kafka-statefulset.yaml
- redis-deployment.yaml
