apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-model-cache
spec:
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/bdc-model-cache
    type: DirectoryOrCreate
