apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-model-cache
spec:
  storageClassName: manual
  volumeName: ai-model-cache
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
