"""
ai-service/mcp/auth.py

MCP API Key Authentication (Static env keys + DB dynamic keys).

Design:
  - Supports static API keys configured via MCP_API_KEYS env var ("key:user_id").
  - ALSO supports self-service dynamic API keys generated by users via the UI
    and stored in PostgreSQL (`mcp_api_keys` table), cached in Redis for speed.
  - Rate limiting is enforced per key using Redis counter with 60s TTL.
  - Keys must be sent as: Authorization: Bearer <key>
"""
from __future__ import annotations

import hashlib
import json
import logging
from contextvars import ContextVar
from typing import Optional

from fastapi import Header, HTTPException, status

from app.core.config import get_settings

logger = logging.getLogger(__name__)
settings = get_settings()


def _parse_api_keys() -> dict[str, int]:
    """Parse static MCP_API_KEYS env var into a dict of {api_key: user_id}."""
    raw = settings.mcp_api_keys.strip()
    if not raw:
        return {}

    mapping: dict[str, int] = {}
    for pair in raw.split(","):
        pair = pair.strip()
        if not pair:
            continue
        if ":" not in pair:
            logger.warning("MCP_API_KEYS: skipping malformed pair %r (missing ':')", pair)
            continue
        key, _, uid_str = pair.partition(":")
        key = key.strip()
        uid_str = uid_str.strip()
        if not key or not uid_str:
            logger.warning("MCP_API_KEYS: skipping empty key or user_id in pair %r", pair)
            continue
        try:
            mapping[key] = int(uid_str)
        except ValueError:
            logger.warning("MCP_API_KEYS: user_id %r is not an integer, skipping", uid_str)
    return mapping


_KEY_MAP: dict[str, int] = _parse_api_keys()
_CURRENT_SCOPES: ContextVar[frozenset[str]] = ContextVar(
    "mcp_scopes", default=frozenset({"read"})
)


def _token_hash(token: str) -> str:
    return hashlib.sha256(token.encode("utf-8")).hexdigest()


def get_current_scopes() -> frozenset[str]:
    """Scopes for the authenticated request, propagated without exposing its token."""
    return _CURRENT_SCOPES.get()


def _get_key_map() -> dict[str, int]:
    """Return the current static key map. Allows tests to patch _KEY_MAP."""
    return _KEY_MAP


def _extract_bearer(authorization: Optional[str]) -> Optional[str]:
    """Extract the token from 'Authorization: Bearer <token>'."""
    if not authorization:
        return None
    scheme, _, token = authorization.partition(" ")
    if scheme.lower() != "bearer":
        return None
    return token.strip() or None


async def _check_rate_limit(api_key: str) -> None:
    """Enforce rate limiting using Redis."""
    if settings.mcp_rate_limit_rpm <= 0:
        return

    try:
        from app.core.cache import get_cache
        redis = await get_cache()

        redis_key = f"mcp:ratelimit:{_token_hash(api_key)}"
        current: Optional[int] = await redis.get(redis_key)

        if current is None:
            await redis.set(redis_key, 1, ex=60)
            return

        count = int(current)
        if count >= settings.mcp_rate_limit_rpm:
            logger.warning(
                "MCP rate limit exceeded",
                extra={"api_key_prefix": api_key[:12], "count": count},
            )
            raise HTTPException(
                status_code=status.HTTP_429_TOO_MANY_REQUESTS,
                detail={
                    "error": "Rate limit exceeded",
                    "limit": settings.mcp_rate_limit_rpm,
                    "window_seconds": 60,
                    "retry_after": 60,
                },
            )
        await redis.incr(redis_key)
    except HTTPException:
        raise
    except Exception as exc:
        logger.warning("MCP rate limit check skipped (Redis error): %s", exc)


async def _resolve_db_key(token: str) -> Optional[tuple[int, frozenset[str]]]:
    """Look up key in Redis cache first, then PostgreSQL DB table `mcp_api_keys`."""
    try:
        from app.core.cache import get_cache
        redis = await get_cache()
        token_hash = _token_hash(token)
        cached = await redis.get(f"mcp:key:{token_hash}")
        if cached is not None:
            payload = json.loads(cached)
            return int(payload["user_id"]), frozenset(payload.get("scopes") or ["read"])
    except Exception:
        pass

    try:
        from app.core.database import get_ai_conn
        async with get_ai_conn() as conn:
            token_hash = _token_hash(token)
            row = await conn.fetchrow(
                """SELECT id, user_id, scopes FROM mcp_api_keys
                   WHERE key_hash = $1 AND revoked_at IS NULL
                     AND (expires_at IS NULL OR expires_at > NOW())""",
                token_hash,
            )
            if row:
                uid = int(row["user_id"])
                scopes = frozenset(row["scopes"] or ["read"])
                # Cache in Redis for 5 minutes
                try:
                    from app.core.cache import get_cache
                    redis = await get_cache()
                    await redis.set(
                        f"mcp:key:{token_hash}",
                        json.dumps({"user_id": uid, "scopes": sorted(scopes)}),
                        ex=300,
                    )
                except Exception:
                    pass
                # Async touch last_used_at
                await conn.execute(
                    "UPDATE mcp_api_keys SET last_used_at = NOW() WHERE id = $1", row["id"]
                )
                return uid, scopes
    except Exception as exc:
        logger.warning("MCP DB key lookup failed: %s", exc)

    return None


async def get_mcp_user_id(
    authorization: Optional[str] = Header(default=None),
) -> int:
    """
    FastAPI dependency: validate MCP API key (from static env or DB) and return user_id.
    """
    if not settings.mcp_enabled:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={"error": "MCP server is disabled", "code": "MCP_DISABLED"},
        )

    token = _extract_bearer(authorization)
    if not token:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={"error": "Missing or invalid Authorization header", "code": "MCP_UNAUTHORIZED"},
            headers={"WWW-Authenticate": "Bearer"},
        )

    # 1. Try static env keys first
    key_map = _get_key_map()
    user_id = key_map.get(token)
    scopes = frozenset({"read", "write"}) if user_id is not None else frozenset()

    # 2. Try database keys
    if user_id is None:
        resolved = await _resolve_db_key(token)
        if resolved is not None:
            user_id, scopes = resolved

    if user_id is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail={"error": "Invalid API key", "code": "MCP_INVALID_KEY"},
            headers={"WWW-Authenticate": "Bearer"},
        )

    await _check_rate_limit(token)
    _CURRENT_SCOPES.set(scopes)

    logger.debug("MCP auth OK", extra={"api_key_prefix": token[:12], "user_id": user_id})
    return user_id
